### ISSUE TITLE
UIViewController+BackButtonhandler issues

### ISSUE THREAD

**Issue by tinora** [apploft/APLUIKitExtension#3]
(-) Please add the License Header of the original creator to the file
(-) Make the 'shouldPopOnBackButtonPress' optional in the protocol, check in the implementation whether the caller implements this method or not and only call it in case he does
(-) Check if the workaround for iOS 7.1 (as mentioned in the original source) ist still necessary
(-) Test, if the implementation is really working as expected in a sample project

**Comment by Ali-Pourasad** [comment]
(-)✅
(-) Could not implement 'shouldPopOnBackButtonPress' as an optional protocol, mainly because the swift compiler does not know the selecotr of the optional function unless you cast types, which makes Xcode always throw a warning.
To avoid this unmutable warning I implemented 'shouldPopOnBackButtonPress' as an default function of UIViewControllers, which always returns true. View controllers need to override this function if they want to modify the default behaviour. Personally, I like this approach more since I think it is cleaner.
(-) The workaround does not seem necessary anymore, although I suggest to keep it in, since I could only test with one device on iOS 13.1. Keeping it in does not affect the excepted behaviour.
(-)✅
